language: node_js
node_js:
- '12'
before_install:
- npm install jest
script:
- npm run test
deploy:
  provider: npm
  email: me@nickdmartin.com
  api_key: $NPM_TOKEN
  on:
    repo: n1ckdm/random-desserts
  skip_cleanup: 'true'
